Error in GetUser System.InvalidOperationException: La secuencia no contiene elementos
   en System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__0[TResult](IEnumerable`1 sequence)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   en System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   en System.Linq.Queryable.First[TSource](IQueryable`1 source)
   en ASarWebApi.Models.UserOperations.UserExist(Int32 id) en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Models\UserOperations.cs:línea 17
   en ASarWebApi.Controllers.UserController.<GetUser>d__4.MoveNext() en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Controllers\UserController.cs:línea 42
--------------------------------------------------------------------------------------------------------
Error in GetUser System.InvalidOperationException: La secuencia no contiene elementos
   en System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__0[TResult](IEnumerable`1 sequence)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   en System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   en System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   en System.Linq.Queryable.First[TSource](IQueryable`1 source)
   en ASarWebApi.Models.UserOperations.UserExist(Int32 id) en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Models\UserOperations.cs:línea 17
   en ASarWebApi.Controllers.UserController.<GetUser>d__4.MoveNext() en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Controllers\UserController.cs:línea 42
--------------------------------------------------------------------------------------------------------
Error in PutUser System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
   en System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   en System.Data.Entity.Core.Objects.ObjectQuery`1.System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>.GetAsyncEnumerator()
   en System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<FirstAsync>d__1d`1.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en ASarWebApi.Models.UserOperations.<GetUser>d__2.MoveNextError in GetALLUser System.Exception: Se produjo una excepción de tipo 'System.Exception'.
   en ASarWebApi.Controllers.UserController.<GetALLUser>d__3.MoveNext() en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Controllers\UserController.cs:línea 28
--------------------------------------------------------------------------------------------------------
Error in GetALLUser System.Exception: Se produjo una excepción de tipo 'System.Exception'.
   en ASarWebApi.Controllers.UserController.<GetALLUser>d__3.MoveNext() en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Controllers\UserController.cs:línea 28
--------------------------------------------------------------------------------------------------------
Error in GetALLUser System.Exception: Se produjo una excepción de tipo 'System.Exception'.
   en ASarWebApi.Controllers.UserController.<GetALLUser>d__3.MoveNext() en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Controllers\UserController.cs:línea 28
--------------------------------------------------------------------------------------------------------
Error in GetALLUser System.Exception: Se produjo una excepción de tipo 'System.Exception'.
   en ASarWebApi.Controllers.UserController.<GetALLUser>d__3.MoveNext() en C:\Users\aleja\Source\Repos\WebApiRest\ASarWebApi\ASarWebApi\Controllers\UserController.cs:línea 28
--------------------------------------------------------------------------------------------------------
